### ISSUE TITLE
Better build system

### ISSUE THREAD

**Issue by gr-im** [xvw/js_of_ocaml_bootstrapper#3]
Hmm actually, the build system is absolutely ... hard. 
We should use a tool like oasis or ocamlbuild to provide an ocamlfind package (and refragmented Bootstrapper module ...)

**Comment by xvw** [comment]
Hum, of course. But I don't have time (so mouch Erlang's work)

**Comment by gr-im** [comment]
No problem. I can have a reflection for you about that. 
Good luck for your work ;)

**Comment by xvw** [comment]
it's now compiled with OASIS
