### ISSUE TITLE
Binding of Small API

### ISSUE THREAD

**Issue by gr-im** [xvw/js_of_ocaml_bootstrapper#8]
La direction principale du projet semble être orientée vers un outil pour construire des prototypes 
facilement (notamment lors de Hackathon... (encore bravo pour ton résultat)). Je suppose donc 
qu'il faudrait préparer des binding pour des API connues (comme MapBox par exemple)? 

Ma proposition serait de créer un module général exposant les clés d'API (pour ceux en requierant).
Le message suivant, si tu es d'accord, portera sur la liste des binding "indispensables".

**Comment by gr-im** [comment]
- [ ] MapBox.js

**Comment by xvw** [comment]
Oui, je pense qu'un module "API" avec des clés pour toutes les API's implémentées est une bonne idée ;) (merci pour ton taff)

**Comment by xvw** [comment]
J'ai bien vu ta primitive "load_library" et je l'ai généralisée dans un foncteur (similaire à Application). 
J'aurais du le faire pour Ehtml aussi mais je m'interroge "encore" sur son intérêt. 
Donc pour inclure des assets, on peut soit utiliser ta méthode, avec `load_library` chaque fois que l'on en a besoin, soit : 

``` ocaml
(* Sample *)
module App =
  Bootstrapper.Application_with(
  struct
    open Bootstrapper
    let context = [
      `Css "loader.css";
      `Js "loaderex.js"
    ]
    let initialize () =
      alert "done"            
  end
  )

```

de cette manière.

**Comment by gr-im** [comment]
J'aime bien ! 
(je me posais les même question pour Ehtml... mais ce serait peut être un peu prématuré de le ... supprimer ;) )

J'ai un peu revu ma position "sur un module qui exporte les APIKeys", ça demande de la configuration, et je n'aime pas trop ça. On pourrait penser une approche avec une fonction d'initialisation, par exemple pour MapBox : `Mapbox.initialize api_key` qui load les assets et prépare une variable avec une APIKey ?

**Comment by xvw** [comment]
Je ferme pour le moment (pour se focaliser sur des points génériques de la lib)

**Comment by xvw** [comment]
(d'autant plus que je ne suis plus convaincu par l'idée de binder, dans le bootstrapper, de petites API's, on peut en discuter si tu veux ;) )
